version: '3.8'
services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: dockerfile
    restart: on-failure
    networks:
      - jenkins-automated
    volumes:
      - ./casc_configs:/var/jenkins_home/casc_configs
      - ./ansible/inventory.ini:/usr/share/jenkins/ref/inventory.ini
      - ./ansible/playbook.yml:/usr/share/jenkins/ref/playbook.yml
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml
    ports:
      - '8080:8080'
      - '50000:50000'
      - '8081:8081'

networks:
  jenkins-automated:
    external: true